<Project Sdk="Microsoft.NET.Sdk.Razor">

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.AspNetCore.Components.Infrastructure" />
    <Using Include="Microsoft.AspNetCore.Components.WebAssembly.Hosting" />
    <Using Include="Microsoft.Extensions.DependencyInjection" />
    <Using Include="Microsoft.Extensions.Http" />
    <Using Include="Microsoft.Extensions.Logging" />
    <Using Include="Microsoft.Extensions.Options" />
    <Using Include="OpenTelemetry" />
    <Using Include="OpenTelemetry.Logs" />
    <Using Include="OpenTelemetry.Metrics" />
    <Using Include="OpenTelemetry.Resources" />
    <Using Include="OpenTelemetry.Trace" />
    <Using Include="OpenTelemetry.Exporter" />
    <Using Include="Polly" />
    <Using Include="Microsoft.Extensions.Http.Resilience" />
    <Using Include="Microsoft.Extensions.ServiceDiscovery" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
    <PackageReference Include="Microsoft.Extensions.ServiceDiscovery" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
  </ItemGroup>

</Project>
