<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Aspire.Hosting.AWS" Version="13.2.0" />
    <PackageVersion Include="Aspire.Hosting.Blazor" Version="13.4.2-preview.1.26303.6" />
    <PackageVersion Include="Aspire.Hosting.Browsers" Version="13.4.2-preview.1.26303.6" />
    <PackageVersion Include="Aspire.Hosting.DevTunnels" Version="13.4.2" />
  </ItemGroup>

  <ItemGroup>
    <PackageVersion Include="Amazon.Lambda.AspNetCoreServer" Version="9.2.1" />
  </ItemGroup>

  <ItemGroup>
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.5" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="10.0.8" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.8" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
    <PackageVersion Include="Microsoft.Extensions.Http.Resilience" Version="10.5.0" />
    <PackageVersion Include="Microsoft.Extensions.ServiceDiscovery" Version="10.5.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.15.3" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.15.3" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.15.2" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AWS" Version="1.15.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AWSLambda" Version="1.15.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.15.1" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Runtime" Version="1.15.1" />
  </ItemGroup>

</Project>
