<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="AWSSDK.DynamoDBv2" />
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PuckDrop.Application\PuckDrop.Application.csproj" />
  </ItemGroup>

</Project>
